model:
  type: "GPT"
  input_dim: 1 # Always 1
  output_dim: 1 # Always 1
  n_layer: 2
  n_head: 4
  n_embd: 32
  dropout: 0.1
  bias: false
  is_causal: true  # Whether to use causal masking in self-attention
  num_pix: (21) # Tuple, (21, 21) for 2D or (21) for 1D
  
  # RegressionTCN hyperparameters
  reg_tcn_kernel_size: 5
  reg_tcn_num_channels: [[16, 16, 32, 64, 64]]
  reg_tcn_dilation_base: 2
  reg_tcn_stride: 1
  reg_tcn_activation: 'GELU'
  reg_tcn_dropout: 0.1

training:
  max_epochs: 500
  batch_size: 256
  optimizer: "Adam"
  learning_rate: 1e-3
  eta_min: 0
  accelerator: "gpu"
  devices: '1'
  use_logging: true
  wandb_project: "triple_correlation"
  experiment_name: "dynamic_weight_test"
  checkpoint_dir: "./biphase/transformer/checkpoints"

loss:
  dynamic: true
  encoding_weight: 1.0

data:
  data_dir: "./biphase/transformer/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 7
  dataset_params:
    train_samples: 10000
    val_samples: 1000
    test_samples: 1000
