model:
  type: "GPT"
  n_layer: 1
  n_head: 4
  n_embd: 16
  dropout: 0.1
  bias: false
  is_causal: true  # Whether to use causal masking in self-attention
  num_pix: 11

training:
  max_epochs: 500
  batch_size: 16
  optimizer: "SGD"
  learning_rate: 5e-4
  eta_min: 0
  accelerator: "cpu"
  devices: '1'
  use_logging: false
  wandb_project: "triple_correlation"
  experiment_name: "updated_encoding"
  checkpoint_dir: "./biphase_gpt/checkpoints"

loss:
  encoding_weight: 1.0

data:
  data_dir: "./biphase_gpt/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 7
  dataset_params:
    train_samples: 100000
    val_samples: 1000
    test_samples: 1000