model:
  type: "GPT"
  n_layer: [1,2,4]
  n_head: 4
  n_embd: [16,32,64]
  dropout: 0.1
  bias: false
  is_causal: true  # Whether to use causal masking in self-attention
  num_pix: (11,11)

training:
  max_epochs: 500
  batch_size: 512
  optimizer: ["SGD", "Adam"]
  learning_rate: 5e-4
  eta_min: 0
  accelerator: "gpu"
  devices: '1'
  use_logging: true
  wandb_project: "triple_correlation"
  experiment_name: "2D_modelsearch_no_encoding_sgd_adam"
  checkpoint_dir: "./biphase_gpt/checkpoints"

loss:
  use_encoding_loss: false
  encoding_weight: 1.0

data:
  data_dir: "./biphase_gpt/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 7
  dataset_params:
    train_samples: 100000
    val_samples: 1000
    test_samples: 1000