model:
  type: "GPT"
  n_layer: 2
  n_head: 2
  n_embd: 16
  dropout: 0.1
  bias: false
  is_causal: true  # Whether to use causal masking in self-attention
  num_pix: (21, 21) # Tuple for 2D phase prediction

training:
  max_epochs: 500
  batch_size: 256
  optimizer: "Adam"
  learning_rate: 5e-4
  eta_min: 0
  accelerator: "gpu"
  devices: '1'
  use_logging: true
  wandb_project: "triple_correlation"
  experiment_name: "updated_encoding_2D"
  checkpoint_dir: "./biphase/transformer/checkpoints"

loss:
  encoding_weight: 1.0

data:
  data_dir: "./biphase/transformer/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 7
  dataset_params:
    train_samples: 10000
    val_samples: 1000
    test_samples: 1000