model:
  n_layer: [4, 6, 8]
  n_head: [4, 8]
  n_embd: [64, 128, 256]
  dropout: [0.1, 0.2]
  bias: [true]

training:
  learning_rate: [1e-4, 3e-4, 1e-3]
  weight_decay: [0.1, 0.2]
  batch_size: [32, 64]
  max_epochs: [50]
  warmup_iters: [100, 500]

data:
  train_path: "./data/train.h5"
  val_path: "./data/val.h5"
  test_path: "./data/test.h5"
  num_workers: 4
