model:
  type: "GPT"
  n_layer: 1
  n_head: 4
  n_embd: 128
  dropout: 0.1
  bias: false
  is_causal: false  # Whether to use causal masking in self-attention

training:
  max_epochs: 50
  batch_size: 512
  optimizer: "Adam"
  learning_rate: 3e-4
  accelerator: "cpu"
  devices: '1'
  use_logging: false
  wandb_project: "triple_correlation"
  experiment_name: "biphase_gpt"
  checkpoint_dir: "./biphase_gpt/checkpoints"
  random_seed: 42

loss:
  use_encoding_loss: true
  encoding_weight: 1.0
  unpack_diagonals: true

data:
  data_dir: "./biphase_gpt/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 4
  dataset_params:
    train_samples: 1000
    val_samples: 100
    test_samples: 100
    num_pix: 21
