model:
  type: "GPT"
  n_layer: 2
  n_head: 4
  n_embd: 128
  dropout: 0.1
  bias: false
  is_causal: false  # Whether to use causal masking in self-attention

training:
  max_epochs: 10
  batch_size: 64
  optimizer: "Adam"
  learning_rate: 5e-4
  T_max: 500
  eta_min: 0
  accelerator: "cpu"
  devices: '1'
  use_logging: true
  wandb_project: "triple_correlation"
  experiment_name: "num_pix_scaling"
  checkpoint_dir: "./biphase_gpt/checkpoints"

loss:
  use_encoding_loss: true
  encoding_weight: 1.0
  unpack_diagonals: false

data:
  data_dir: "./biphase_gpt/data"
  train_file: "train.h5"
  val_file: "val.h5"
  test_file: "test.h5"
  num_workers: 4
  dataset_params:
    train_samples: 100
    val_samples: 1000
    test_samples: 100
    num_pix: 11
